services:
  worker:
    image: myoung34/github-runner:latest
    env_file: .env
    environment: 
      RUNNER_WORKDIR: /tmp/runner-work
      RUNNER_SCOPE: 'repo'
      LABELS: linux,arm64
    security_opt:
      # needed on SELinux systems to allow docker container to manage other docker containers
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner-work:/tmp/runner-work'
      # note: a quirk of docker-in-docker is that this path
      # needs to be the same path on host and inside the container,
      # docker mgmt cmds run outside of docker but expect the paths from within