services:
  worker:
    image: myoung34/github-runner:latest
    env_file: .env
    environment: 
      RUNNER_WORKDIR: /tmp/runner-work
      RUNNER_SCOPE: 'repo'
      EPHEMERAL: 1
      LABELS: linux,arm64
    security_opt:
      # needed on SELinux systems to allow docker container to manage other docker containers
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
